author: CmdrDats
database: false
description: "Building planner lets you mark out a zone for planning structures. When\
  \ you enter that zone, you will enter a special 'mode' where you'll have access\
  \ to every placeable block and you'll be able to instantly delete blocks.\r\n\r\n\
  Once your planning is complete, the building will disappear and then you fill a\
  \ special chest with the required building materials, as you fill it, the building\
  \ will build itself!"
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: za.dats.bukkit.buildingplanner.BuildingPlanner
name: BuildingPlanner
startup: postworld
url: https://github.com/CmdrDats/BuildingPlanner
version: '0.5.2'
commands:
  plan:
    aliases: [plancommand]
    description: Building Planner commands
    usage: |
      Usage: /<command> version
      Usage: /<command> version playername
permissions:
  buildingplanner.*:
    description: gives access to all BuildingPlanner permissions
    children:
      buildingplanner.anyarea: true
      buildingplanner.create: true
      buildingplanner.destroy: true
      buildingplanner.use: true
      buildingplanner.commit: true
      buildingplanner.uncommit: true
      buildingplanner.list: true
      buildingplanner.report: true
      buildingplanner.send: true
      buildingplanner.invite: true
      buildingplanner.give: true
  buildingplanner.architect:
    description: access to architect level permissions (creating/destroying plans)
    children:
      buildingplanner.anyarea: false
      buildingplanner.create: true
      buildingplanner.destroy: true
      buildingplanner.use: true
      buildingplanner.commit: true
      buildingplanner.uncommit: true
      buildingplanner.list: true
      buildingplanner.report: true
      buildingplanner.send: true
      buildingplanner.invite: true
      buildingplanner.give: true
  buildingplanner.planner:
    description: access to planning level permissions (use, commit, uncommit, etc.)
    children:
      buildingplanner.anyarea: false
      buildingplanner.create: false
      buildingplanner.destroy: false
      buildingplanner.use: true
      buildingplanner.commit: true
      buildingplanner.uncommit: true
      buildingplanner.list: false
      buildingplanner.report: true
      buildingplanner.send: false
      buildingplanner.invite: false
      buildingplanner.give: false
  buildingplanner.anyarea:
    description: Allowed to destroy/commit/uncommit/modify any area (even if not owner or collaborator)
    default: op
  buildingplanner.create:
    description: Allows player to define a building area
    default: true
  buildingplanner.destroy:
    description: Allows player to cancel a building area (by breaking the sign)
    default: true
  buildingplanner.use:
    description: Allows player to use planning areas
    default: true
  buildingplanner.commit:
    description: Allows player to commit planning areas
    default: true
  buildingplanner.uncommit:
    description: Allows player to uncommit planning areas
    default: true
  buildingplanner.list:
    description: Allow a player to list all areas
    default: op
  buildingplanner.report:
    description: Allow a player to report on area building materials with /plan report command
    default: true
  buildingplanner.send:
    description: Allow a player to send a report on area building materials with /plan send command
    default: true    
  buildingplanner.invite:
    description: Allow a player to invite collaborators to their plan
    default: true       
  buildingplanner.give:
    description: Allow a player to give away their plan areas.
    default: true             